package Clases;
// Generated 24-jun-2018 15:53:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Comuna comuna;
     private EstadoCivil estadoCivil;
     private EstadoPostulacion estadoPostulacion;
     private NvlEducacional nvlEducacional;
     private Renta renta;
     private String rut;
     private String nombre;
     private String apePat;
     private String apeMat;
     private Date fechaNac;
     private String sexo;
     private Integer hijos;
     private String correo;
     private String telefono;
     private String direccion;
     private String sueldoLiquido;
     private Character enfermedad;

    public Cliente() {
    }

    public Cliente(Comuna comuna, EstadoCivil estadoCivil, EstadoPostulacion estadoPostulacion, NvlEducacional nvlEducacional, Renta renta, String rut, String nombre, String apePat, String apeMat, Date fechaNac, String sexo, Integer hijos, String correo, String telefono, String direccion, String sueldoLiquido, Character enfermedad) {
       this.comuna = comuna;
       this.estadoCivil = estadoCivil;
       this.estadoPostulacion = estadoPostulacion;
       this.nvlEducacional = nvlEducacional;
       this.renta = renta;
       this.rut = rut;
       this.nombre = nombre;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.hijos = hijos;
       this.correo = correo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.sueldoLiquido = sueldoLiquido;
       this.enfermedad = enfermedad;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Comuna getComuna() {
        return this.comuna;
    }
    
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public EstadoPostulacion getEstadoPostulacion() {
        return this.estadoPostulacion;
    }
    
    public void setEstadoPostulacion(EstadoPostulacion estadoPostulacion) {
        this.estadoPostulacion = estadoPostulacion;
    }
    public NvlEducacional getNvlEducacional() {
        return this.nvlEducacional;
    }
    
    public void setNvlEducacional(NvlEducacional nvlEducacional) {
        this.nvlEducacional = nvlEducacional;
    }
    public Renta getRenta() {
        return this.renta;
    }
    
    public void setRenta(Renta renta) {
        this.renta = renta;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getHijos() {
        return this.hijos;
    }
    
    public void setHijos(Integer hijos) {
        this.hijos = hijos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getSueldoLiquido() {
        return this.sueldoLiquido;
    }
    
    public void setSueldoLiquido(String sueldoLiquido) {
        this.sueldoLiquido = sueldoLiquido;
    }
    public Character getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(Character enfermedad) {
        this.enfermedad = enfermedad;
    }




}


