package Clases;
// Generated 24-jun-2018 15:53:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoPostulacion generated by hbm2java
 */
public class EstadoPostulacion  implements java.io.Serializable {


     private int idEstado;
     private String nomEstado;
     private Set estadoPostulacion = new HashSet(0);

    public EstadoPostulacion() {
    }

	
    public EstadoPostulacion(int idEstado) {
        this.idEstado = idEstado;
    }
    public EstadoPostulacion(int idEstado, String nomEstado, Set estadoPostulacion) {
       this.idEstado = idEstado;
       this.nomEstado = nomEstado;
       this.estadoPostulacion = estadoPostulacion;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public String getNomEstado() {
        return this.nomEstado;
    }
    
    public void setNomEstado(String nomEstado) {
        this.nomEstado = nomEstado;
    }
    public Set getClientes() {
        return this.estadoPostulacion;
    }
    
    public void setClientes(Set estadoPostulacion) {
        this.estadoPostulacion = estadoPostulacion;
    }




}


