package Clases;
// Generated 24-jun-2018 15:53:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoCivil generated by hbm2java
 */
public class EstadoCivil  implements java.io.Serializable {


     private Integer idEstadoCivil;
     private String nomEstado;
     private Set estadoCivil = new HashSet(0);

    public EstadoCivil() {
    }

    public EstadoCivil(String nomEstado, Set estadoCivil) {
       this.nomEstado = nomEstado;
       this.estadoCivil = estadoCivil;
    }
   
    public Integer getIdEstadoCivil() {
        return this.idEstadoCivil;
    }
    
    public void setIdEstadoCivil(Integer idEstadoCivil) {
        this.idEstadoCivil = idEstadoCivil;
    }
    public String getNomEstado() {
        return this.nomEstado;
    }
    
    public void setNomEstado(String nomEstado) {
        this.nomEstado = nomEstado;
    }
    public Set getClientes() {
        return this.estadoCivil;
    }
    
    public void setClientes(Set estadoCivil) {
        this.estadoCivil = estadoCivil;
    }




}


